### ISSUE TITLE
Is there any document or tutorial for this project?

### ISSUE THREAD

**Issue by waitingkuo** [harshavardhana/boilerpipy#2]
I was a user of boilerpipe (the Java one). I'm quiet interested in the Python one! Is there any tutorial or a simple Getting start article for this?

Thanks!

**Comment by harshavardhana** [comment]
> I was a user of boilerpipe (the Java one). I'm quiet interested in the Python one! Is there any tutorial or a simple Getting start article for this?

Oh yeah, that i have to get to :-) -  but it is simple.  If you are okay reading code..  - https://github.com/harshavardhana/boilerpipy/blob/master/bin/readability 

In a nutshell its just this 

```
import logging

try:
    import urllib.request as compat_urllib_request
except ImportError: # Python 2
    import urllib2 as compat_urllib_request

url = compat_urllib_request.urlopen("your_url")
content = url.read()

out = Extractor(content, loglevel=logging.INFO).extracted()
print(out.encode('utf-8','ignore'))
```

**Comment by waitingkuo** [comment]
This is good! I'll read your code. Thanks!
